(defun print-dotted-paired-exp (exp)
  (cond ((null exp) (princ nil))
        ((listp exp)
         (princ "(")
         (print-dotted-paired-exp (car exp))
         (princ " . ")
         (print-dotted-paired-exp (cdr exp))
         (princ ")"))
        ((atom exp)
         (princ exp))))
(print-dotted-paired-exp '(+ 1 2))
