(defun print-dotted-paired-exp-2 (exp)
  (cond ((null exp) (princ nil))
        ((atom exp)
         (princ exp))
        ((listp exp)
         (cond ((null (cdr (last exp)))
                (print exp))
               (t
                (princ "(")
                (print-dotted-paired-exp-2 (car exp))
                (princ " . ")
                (print-dotted-paired-exp-2 (cdr exp))
                (princ ")"))))))
(print-dotted-paired-exp-2 (list 1 2 (cons 1 2)))
